using DocumentFormat.OpenXml.Spreadsheet;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using System;

namespace YourAppNamespace.Reports
{
    public class TimelinePdfDocument : IDocument
    {
        private readonly byte[] _chartImage;
        private readonly string _title;
        private readonly DateTime _startDate;
        private readonly DateTime _endDate;

        // Constructor (matching your controller)
        public TimelinePdfDocument(byte[] chartImage, string title, DateTime startDate, DateTime endDate)
        {
            _chartImage = chartImage;
            _title = title;
            _startDate = startDate;
            _endDate = endDate;
        }

        // Document metadata
        public DocumentMetadata GetMetadata() => new DocumentMetadata
        {
            Title = _title
        };

        // Create PDF
        public void Compose(IDocumentContainer container)
        {
            container.Page(page =>
            {
                page.Margin(40);

                // 🔹 Header
                page.Header().Height(60).Background("#dc3545").Padding(15).Row(row =>
                {
                    row.RelativeItem().AlignLeft().Text(_title)
                        .FontSize(18).SemiBold().FontColor("White");

                    row.RelativeItem().AlignRight()
                        .Text($"From: {_startDate:dd-MMM-yyyy}\nTo: {_endDate:dd-MMM-yyyy}")
                        .FontSize(10).FontColor("White");
                });

                // 🔹 Content
                page.Content().PaddingVertical(10).Column(col =>
                {
                    col.Item().PaddingBottom(10).Text("Reservation Timeline Chart")
                        .FontSize(16).SemiBold().FontColor("#333333");

                    col.Item().PaddingBottom(10).Text($"Generated On: {DateTime.Now:dd-MMM-yyyy HH:mm}")
                        .FontSize(10).FontColor("#777777");

                    // Chart Image
                    col.Item()
                        .PaddingTop(10)
                        .Element(ComposeChartImage);
                });

                // 🔹 Footer
                page.Footer().Background("#f8f9fa").Padding(10).Row(row =>
                {
                    row.RelativeItem().AlignLeft().Text("Generated by Anandashram System")
                        .FontSize(10).FontColor("#888");

                    row.RelativeItem().AlignRight().Text(text =>
                    {
                        text.Span("Page ");
                        text.CurrentPageNumber().FontSize(10).FontColor("#888");
                    });
                });
            });
        }

        // Chart image renderer
        void ComposeChartImage(QuestPDF.Infrastructure.IContainer container)
        {
            if (_chartImage != null && _chartImage.Length > 0)
            {
                container
                    .Background("#ffffff")
                    .Border(1)
                    .BorderColor("#cccccc")
                    .Padding(10)
                    .AlignCenter()
                    .Image(_chartImage, ImageScaling.FitWidth);
            }
            else
            {
                container.Text("Chart not available")
                    .FontSize(14).FontColor("#cc0000");
            }
        }
    }
}
